export default{
    SET_RANDOM_RECIPES: 'SET_RANDOM_RECIPES',
    SET_ERROR: 'SET_ERROR',
    SET_RECIPE_DETAILS: 'SET_RECIPE_DETAILS'
    // ADD_FAVORITE_RECIPE: 'ADD_FAVORITE_RECIPE',
    // REMOVE_FAVORITE_RECIPE: 'REMOVE_FAVORITE_RECIPE',
}