export default{
    SET_RANDOM_RECIPES: 'SET_RANDOM_RECIPES',
    SET_ERROR: 'SET_ERROR',
    SET_RECIPE_DETAILS: 'SET_RECIPE_DETAILS',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    REGISTER_USER: 'REGISTER_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
    LOGIN_USER: 'LOGIN_USER',
    RECIPE_VIEW: 'RECIPE_VIEW',
    SEARCH_BY_INGREDIENT: 'SEARCH_BY_INGREDIENT'
    // ADD_FAVORITE_RECIPE: 'ADD_FAVORITE_RECIPE',
    // REMOVE_FAVORITE_RECIPE: 'REMOVE_FAVORITE_RECIPE',
}