export default{
    SET_RANDOM_RECIPES: 'SET_RANDOM_RECIPES',
    SET_ERROR: 'SET_ERROR',
    SET_RECIPE_DETAILS: 'SET_RECIPE_DETAILS',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_USER: 'REGISTER_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',
    RECIPE_VIEW: 'RECIPE_VIEW',
    SEARCH_BY_INGREDIENT: 'SEARCH_BY_INGREDIENT',
    SET_RANDOM_FOOD_TRIVIA: 'SET_RANDOM_FOOD_TRIVIA',
    SET_RANDOM_FOOD_JOKE: 'SET_RANDOM_FOOD_JOKE'
}